DROP TABLE IF EXISTS flowers CASCADE;
DROP TABLE IF EXISTS bees;

CREATE TABLE flowers (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
color TEXT NOT NULL,
fragrance TEXT NOT NULL,
petals INTEGER CHECK (petals > 0)
);

CREATE TABLE bees (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
bee_name TEXT NOT NULL,
buzz_style TEXT NOT NULL,
fuzzy_factor INTEGER CHECK (fuzzy_factor >= 0),
flower_id BIGINT REFERENCES flowers(id)
);